In [ ]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from function_generation.PolynomialGenerator import PolynomialGenerator
from grad_descent import grad_descent

from experiments.utils.run_experiment

In [ ]:

stoppping_conditions = ["x", "y"]
learning_rates = ["constant", "Armijo", "progress bound"]
epsilon = np.array([0.1 ** (i / 3) for i in range(32)])
# print(epsilon)
num_functions = 20
repeats = 3
bound = 2
dimensions = 3
degree = 2
multiplier = 1
LR = 0.01

lr= learning_rates[0]
sc = stoppping_conditions[0]

results = np.zeros((num_functions * repeats, len(epsilon), dimensions - 2))

for i in range(2, dimensions):
    results[:, :, i - 2] = run_experiment(epsilon=epsilon, num_functions=num_functions, repeats=repeats,
                                          bound=bound, LR=LR,
                                          dimension=i, degree=degree, stopping_condition=sc,
                                          multiplier=multiplier, learning_rate=lr, max_steps=1000)
    print(f"dimension {i} done")

name = f"iter_{num_functions}_repeat_{repeats}_dim_{dimensions}_stop_x_lr_{lr}.npy"
np.save(name, results)


In [ ]:
results = np.load(name)

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5))
x = 1/epsilon
dim = 0

for i in range(0,num_functions*repeats):
    ax.plot(x, results[i,:,dim], label=f"dimension {dim}", alpha=0.05, color="red")
ax.plot(x, results[:, :, dim].mean(axis=0), label=f"dimension {dim}", color="blue")
# ax.set_ylim([10, 15])
ax.set_xlabel("1/epsilon")
ax.set_ylabel("steps")
plt.xscale("log")


In [1]:
import numpy as np
a = np.random.rand(10000,10000)
print(a)
x = np.random.rand(10000,1)
# d = np.max(np.abs(np.linalg.eigvals(a)))
c = x.T@a@x
print(c)

[[0.42495909 0.33726354 0.3171271  ... 0.55111055 0.39220891 0.19588557]
 [0.35438042 0.73235588 0.62105906 ... 0.89634721 0.99797795 0.16364404]
 [0.74651001 0.2411931  0.64236654 ... 0.47361318 0.66711197 0.67359928]
 ...
 [0.92160251 0.51304628 0.78475515 ... 0.44158144 0.62577912 0.18393031]
 [0.38990232 0.48485955 0.35976059 ... 0.84550687 0.99915933 0.20492783]
 [0.76779142 0.40012927 0.93565979 ... 0.80774653 0.06452096 0.66351173]]
[[12640331.35734968]]
